# Generated by Django 4.1.7 on 2023-04-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_custuser_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custuser',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.custuser'),
        ),
    ]
